name: Generate MySky EPG

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, json

      - name: Ensure Output Directory Exists
        run: mkdir -p output

      - name: Execute MySky EPG Generation Script
        run: php source/mysky.php

      - name: Check MySky Output File
        run: ls -l output/mysky.xml || echo "MySky file not found"

      - name: Commit and Push MySky Changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated MySky EPG data generation (every 2 hours)"
          file_pattern: output/mysky.xml

      - name: Pull latest changes
        run: git pull origin main --rebase
