name: Generate Blast EPG (Daily - Output Root)

permissions:
  contents: write

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for git operations

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, json

      - name: Ensure Output Directory Exists
        run: mkdir -p output

      - name: Execute Blast EPG Generation Script
        run: php source/blast.php

      - name: Check Blast Output File
        run: ls -l output/blast.xml || echo "Blast file not found"

      - name: Commit and Push Blast Changes (Always)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add output/blast.xml

          if git diff --cached --quiet; then
            git commit --allow-empty -m "Daily workflow run: no changes to blast.xml"
          else
            git commit -m "Automated Blast EPG data generation (daily)"
          fi

          git push origin main
