name: Generate CPlay EPG

on:
  schedule:
    - cron: '0 16 * * *' # Runs daily at 16:00 UTC (12:00 AM PHT)
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: json, curl

      - name: Ensure Output Directory Exists
        run: mkdir -p output/individual

      - name: Execute CPlay EPG Generation Script
        run: php source/cplay.php

      - name: Check CPlay Output File
        run: ls -l output/individual/cplay.xml || echo "CPlay file not found"

      - name: Commit and Push CPlay Changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated CPlay EPG data generation"
          file_pattern: output/individual/cplay.xml
